Repository informatik-mannheim/HSMA-CTT, pull requests merged in 2021-09, with the labels that each got.

#200 fixed sometimes occuring nullpointer exception
  src/test/java/de/hs_mannheim/informatik/ct/model/RoomVisitTest.java
Labels: good first issue, back end, test

#214 Hotfix/renamed query param room pin makes qr codes invalid
  src/main/java/de/hs_mannheim/informatik/ct/controller/RoomController.java
  src/main/resources/templates/index.html
Labels: bug

#220 Beautyfied room qr-code flyer template.
  templates/printout/room-printout-privileged.docx
  templates/printout/room-printout.docx
Labels: bad ux

#218 Update layout.html
  src/main/resources/templates/layout.html
Labels: bad ux, front end

#235 Feature/scheduled maintenance task rework
  src/main/java/de/hs_mannheim/informatik/ct/controller/CtController.java
  src/main/java/de/hs_mannheim/informatik/ct/util/ScheduledMaintenanceTasks.java
  src/test/java/de/hs_mannheim/informatik/ct/persistence/integration/ScheduledCheckOut.java
  src/test/java/de/hs_mannheim/informatik/ct/persistence/services/RoomServiceTest.java
Labels: back end, test, high priority
